<?php

/**
 * Implements hook_theme()
 */
function iish_conference_programme_theme() {
  return array(
    'iish_conference_programme' => array(
      'variables' => array(
        'networks' => array(),
        'eventDate' => NULL,
        'days' => NULL,
        'dateTimes' => NULL,
        'types' => NULL,
        'programme' => NULL,
        'backUrlQuery' => NULL,
        'highlight' => NULL,
        'networkId' => NULL,
        'roomId' => NULL,
        'sessionId' => NULL,
        'textsearch' => NULL,
        'curShowing' => NULL,
        'downloadPaperIsOpen' => NULL,
        'favoriteSessions' => array(),
        'isParticipant' => FALSE,
      ),
    ),
  );
}
